language: node_js
node_js:
  - 10.16.3
before_script:
  - npm install
before_deploy:
  - npm run build:prod
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: concept41.com
    skip_cleanup: false
    local_dir: build